"""Render a starter ``.compose-lint.yml`` from lint findings (ADR-011).

``compose-lint init`` runs the rules with no existing config, then hands the raw
findings here to produce a config the user edits to triage suppressions. Every
finding becomes a per-service ``exclude_services`` entry with a placeholder
reason. The encoding is deliberately service-level — never a global
``enabled: false``: naming each service fails safe, so a rule still fires on a
service added to the Compose file later instead of being silently uncovered.

This module is intentionally outside ``formatters/``. It does not satisfy the
``format(findings) -> str`` contract: it needs rule metadata (names) and emits a
different artifact, not rendered findings.
"""

from __future__ import annotations

import re

from compose_lint.models import Finding, Severity

_PLACEHOLDER_REASON = "TODO: justify or fix"
_DOCS_URL = "https://github.com/tmatens/compose-lint/blob/main/docs/configuration.md"

# Sort key for severity, most severe first. Kept local (rather than reaching into
# Severity._rank) so the emitter owns its own public ordering.
_SEVERITY_RANK = {
    Severity.CRITICAL: 3,
    Severity.HIGH: 2,
    Severity.MEDIUM: 1,
    Severity.LOW: 0,
}

# A YAML plain scalar safe to emit unquoted: an identifier-ish token with no
# characters that would change the parse. Anything else is double-quoted.
_PLAIN_SCALAR = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def _scalar(value: str) -> str:
    """Render a string as a YAML scalar, quoting only when necessary."""
    if _PLAIN_SCALAR.match(value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _rule_names() -> dict[str, str]:
    """Map rule id to human name for the per-rule annotation comment."""
    from compose_lint.rules import get_registered_rules

    return {cls().metadata.id: cls().metadata.name for cls in get_registered_rules()}


def render_config(findings: list[Finding]) -> str:
    """Render a starter ``.compose-lint.yml`` from ``findings``.

    ``findings`` must be non-empty; the caller handles the no-findings case.
    Rules are ordered by severity (most severe first), then by id. Services
    within a rule are sorted, and each ``(rule, service)`` pair appears once even
    if a rule fired more than once on the same service.
    """
    by_rule: dict[str, set[str]] = {}
    severities: dict[str, Severity] = {}
    for f in findings:
        by_rule.setdefault(f.rule_id, set()).add(f.service)
        # Severity is rule-stable under the empty config init runs with, so the
        # last writer per rule is as good as any.
        severities[f.rule_id] = f.severity

    names = _rule_names()

    lines = [
        "# .compose-lint.yml — generated by `compose-lint init`",
        "#",
        "# Each entry suppresses a finding compose-lint reported. Replace the",
        "# placeholder reason with a real justification, or delete the entry and",
        "# fix the underlying issue. Suppressed findings still appear in output",
        "# (marked SUPPRESSED) and no longer count toward --fail-on.",
        "#",
        "# Review CRITICAL and HIGH entries first — prefer fixing over suppressing.",
        f"# Docs: {_DOCS_URL}",
        "",
        "rules:",
    ]
    for rule_id in sorted(by_rule, key=lambda r: (-_SEVERITY_RANK[severities[r]], r)):
        label = severities[rule_id].value.upper()
        name = names.get(rule_id)
        if name:
            label = f"{label} — {name}"
        lines.append(f"  {_scalar(rule_id)}:  # {label}")
        lines.append("    exclude_services:")
        for service in sorted(by_rule[rule_id]):
            lines.append(f"      {_scalar(service)}: {_scalar(_PLACEHOLDER_REASON)}")

    return "\n".join(lines) + "\n"
