name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  security-events: write

jobs:
  batch-fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
      - uses: actions/checkout@v6

      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}
          fuzz-seconds: 600
          mode: batch
          output-sarif: true
