name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  batch-fuzzing:
    permissions:
      contents: read
      actions: write
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: python
          sanitizer: ${{ matrix.sanitizer }}
          fuzz-seconds: 600
          mode: batch
          output-sarif: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
